# Generated by Django 5.0.4 on 2024-08-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashYouApp', '0002_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin3s',
            name='role',
            field=models.CharField(choices=[('developper', 'Developper'), ('admin', 'Admin'), ('devops', 'Devops')], default='developper', max_length=10),
        ),
    ]
