# Generated by Django 5.0.4 on 2024-08-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashYouApp', '0003_alter_admin3s_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('devops', 'DevOps'), ('supervisor', 'Supervisor')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='admin3s',
            name='role',
            field=models.CharField(choices=[('developper', 'Developper'), ('admin', 'Admin'), ('supervisor', 'Supervisor'), ('devops', 'Devops')], default='developper', max_length=10),
        ),
    ]
